# Generated by Django 4.2.13 on 2024-06-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
